[book]
title = "豆知識集"
authors = ["kazanefu"]
language = "en"

[output.html]
additional-js = ["theme/highlight.min.js", "theme/wapl.js","theme/wapl-rainbow.js"]
additional-css = ["theme/wapl.css","theme/wapl-rainbow.css"]